Transform: AWS::Serverless-2016-10-31
Description: AWS Resources for the GameAI backend

Parameters:
  Owner:
    Type: String
    Default: jack

  Project:
    Type: String
    Default: GameAI

  AppName:
    Type: String
    Default: Game-AI

Resources:
  # IAM
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      Description: IAM Role allowing GameAI access to DynamoDB
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      RoleName: !Sub Lambda-${AppName}
      Tags:
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  # Lambda
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - arm64
        - x86_64
      CompatibleRuntimes:
        - python3.9
      ContentUri: ./packages
      LayerName: gameai_dependencies

  GameAI:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: ./main
      Description: The GameAI backend
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref AppName
          POWERTOOLS_LOG_LEVEL: INFO
      FunctionName: !Ref AppName
      Handler: app.handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref GameAIHttpApi
            Method: GET
            Path: /health
            PayloadFormatVersion: "2.0"
      Layers:
        - !Ref DependencyLayer
      MemorySize: 512
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Timeout: 900
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  # API Gateway
  GameAIHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: API frontend for the GameAI
      Name: !Sub ${AppName}
      ProtocolType: HTTP
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  GameAIHttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref GameAIHttpApi
      AutoDeploy: true
      StageName: $default
      Tags:
        Owner: !Ref Owner
        Project: !Ref Project

  APIGameAILambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref GameAIHttpApi
      Description: Integration the frontend API with the GameAI lambda
      IntegrationType: AWS_PROXY
      IntegrationUri: !Join
        - ""
        - - "arn:"
          - !Ref "AWS::Partition"
          - ":apigateway:"
          - !Ref "AWS::Region"
          - ":lambda:path/2015-03-31/functions/"
          - !GetAtt GameAI.Arn
          - /invocations
      PayloadFormatVersion: "2.0"

  APIHealthRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref GameAIHttpApi
      AuthorizationType: NONE
      RouteKey: GET /health
      Target: !Join
        - "/"
        - - "integrations"
          - !Ref APIGameAILambdaIntegration
  