Transform: AWS::Serverless-2016-10-31
Description: AWS Resources for the GameAI backend

Resources:
  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - arm64
        - x86_64
      CompatibleRuntimes:
        - python3.9
      ContentUri: packages
      LayerName: gameai_dependencies
